import antigravity

CERT="""-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABBZ9pP87O
nynWOBVEhRx7ICAAAAEAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIANZ2Ah61xzlaDCt
WySbQAgC7NOm5+AqlotnLhZnTUGFAAAAkPRPfHBJdN82fkZpb3n38TcjpWnFmdtfI29Q77
x/GxLuABy47UzPGahMqIaYP1eeq/w+/PP+FwU72HkkoNgkNuBpyRLnx+c6MsohCmCcHQKA
+6Kd59r2MmC1NDBkCzTB3bolVzRiBNwOqZPjEMlkBNYhwXVx2+aAD8EjZwPCYiHiXSp5RP
4RZHgV3LbU9jlX1w==
-----END OPENSSH PRIVATE KEY-----
"""

def main():
    antigravity.fly()

if __name__ == "__main__":
    main()
